name: 'my_business_analytics'
version: '1.0.0'

# Ensure this matches the name of the profile in your profiles.yml file
profile: 'dbt_duckdb_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  my_business_analytics:
    # This applies to everything in the models/Staging/ folder
    Staging:
      +materialized: view
    
    # This applies to everything in the models/Marts/ folder
    Marts:
      +materialized: table
      # You can also be specific for subfolders, like your finance models:
      finance:
        +materialized: table